[package]
name = "ohmygamepad-win-xbox-haptics"
version = "0.1.0"

edition.workspace = true

rust-version.workspace = true

license.workspace = true

authors.workspace = true

publish = false

[dependencies]
ohmygamepad-core = { path = "../../core" }
ohmygamepad-protocol = { path = "../../protocol" }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_Gaming"] }
windows = { version = "0.61.3", features = ["Gaming_Input"] }

[lib]
path = "src/lib.rs"
