[package]
name = "xbxrc"
version = "0.1.0"
description = "A Tauri App"
authors = [ "you" ]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "xbxrc_lib"
crate-type = [
  "staticlib",
  "cdylib",
  "rlib"
]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
async-trait.workspace = true

tauri = { version = "2", features = [
  "macos-private-api",
  "unstable"
] }
tauri-plugin-opener = "2"

serde.workspace = true

serde_json.workspace = true

reqwest.workspace = true

p256.workspace = true

ring.workspace = true

openssl.workspace = true

base64.workspace = true

hmac.workspace = true

sha2.workspace = true

hex-literal.workspace = true

rand_core.workspace = true

uuid.workspace = true

chrono.workspace = true

url.workspace = true

parking_lot.workspace = true

rand.workspace = true

tauri-plugin-shell = "2.3.5"
tauri-plugin-fs = "2.4.5"
tauri-plugin-store = "2.4.2"
tauri-plugin-keepawake = "0.1.1"

tokio.workspace = true

xbxengine = { path = "../crates/xbxengine/core" }
xbxengine-protocol = { path = "../crates/xbxengine/protocol" }
xbox-auth-flow = { path = "../crates/xbox-auth-flow" }
xbox-streaming = { path = "../crates/xbox-streaming" }
xbox-webapi = { path = "../crates/xbox-webapi" }
ohmygamepad-host = { path = "../crates/ohmygamepad/bridge/host" }
ohmygamepad-protocol = { path = "../crates/ohmygamepad/protocol" }

thiserror.workspace = true

log.workspace = true

env_logger.workspace = true

pollster = "0.3.0"
raw-window-handle = "0.6.2"
wgpu = "28.0.0"

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "0.6.4", default-features = false, features = [ "std" ] }
objc2-foundation = { version = "0.3.2", default-features = false, features = [
  "alloc",
  "NSGeometry",
  "NSString"
] }
objc2-app-kit = { version = "0.3.2", default-features = false, features = [
  "NSView",
  "NSWindow"
] }
wgpu-hal = "28.0.0"
metal = "0.33.0"
