[package]
name = "xbxengine"
version = "0.1.0"

edition.workspace = true

rust-version.workspace = true

license.workspace = true

authors.workspace = true

publish = false

[dependencies]
bytes.workspace = true
base64.workspace = true

cpal.workspace = true

async-trait.workspace = true

h264-reader.workspace = true

hex-literal.workspace = true

ohmygamepad-host = { path = "../../ohmygamepad/bridge/host" }
ohmygamepad-protocol = { path = "../../ohmygamepad/protocol" }

opus.workspace = true

rtc-rtp.workspace = true

rtc-rtcp.workspace = true

rtc-media.workspace = true

rtc-shared.workspace = true

rtc-stun.workspace = true

rtc-turn.workspace = true

log.workspace = true

url.workspace = true

serde_json.workspace = true

xbxengine-protocol = { path = "../protocol" }

tokio.workspace = true

rtc.workspace = true

openssl.workspace = true

[lib]
path = "src/lib.rs"
