[package]
name = "xbxengine"
version = "0.1.0"
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
publish = false

[dependencies]
bytes.workspace = true
cpal.workspace = true
async-trait.workspace = true
interceptor.workspace = true
ohmygamepad-host = { path = "../../ohmygamepad/bridge/host" }
ohmygamepad-protocol = { path = "../../ohmygamepad/protocol" }
opus.workspace = true
rtp.workspace = true
rtcp.workspace = true
serde_json.workspace = true
xbxengine-protocol = { path = "../protocol" }
tokio.workspace = true
webrtc.workspace = true
webrtc-media.workspace = true
webrtc-util.workspace = true

[lib]
path = "src/lib.rs"
