[package]
name = "ohmygamepad-host"
version = "0.1.0"

edition.workspace = true

rust-version.workspace = true

license.workspace = true

authors.workspace = true

publish = false

[dependencies]
ohmygamepad-gilrs = { path = "../../backends/gilrs" }
ohmygamepad-macos-gccontroller-haptics = { path = "../../backends/macos-gccontroller-haptics" }
ohmygamepad-win-xbox-haptics = { path = "../../backends/win-xbox-haptics" }
ohmygamepad-core = { path = "../../core" }
ohmygamepad-protocol = { path = "../../protocol" }

[lib]
path = "src/lib.rs"
