[package]
name = "ohmygamepad-macos-gccontroller-haptics"
version = "0.1.0"

edition.workspace = true

rust-version.workspace = true

license.workspace = true

authors.workspace = true

publish = false

[dependencies]
ohmygamepad-core = { path = "../../core" }
ohmygamepad-protocol = { path = "../../protocol" }

[target.'cfg(target_os = "macos")'.dependencies]
objc2 = { version = "0.6.4", default-features = false, features = ["std"] }
objc2-foundation = { version = "0.3.2", default-features = false, features = ["alloc", "NSArray", "NSError", "NSString"] }
objc2-game-controller = { version = "0.3.2", default-features = false, features = ["GCController", "GCDevice", "GCDeviceHaptics"] }
objc2-core-haptics = { version = "0.3.2", default-features = false, features = ["alloc", "CHHapticEngine", "CHHapticEvent", "CHHapticParameter", "CHHapticPattern", "CHHapticPatternPlayer"] }

[lib]
path = "src/lib.rs"
