[package]
name = "ohmygamepad-sdl3"
version = "0.1.0"

edition.workspace = true

rust-version.workspace = true

license.workspace = true

authors.workspace = true

publish = false

[dependencies]
device_query = "4.0.1"
log = "0.4"
ohmygamepad-core = { path = "../../core" }
ohmygamepad-protocol = { path = "../../protocol" }
serde_json = "1"
sdl3 = { version = "0.18.0", features = [
  "build-from-source-static",
  "hidapi"
] }

[target.'cfg(target_os = "windows")'.dependencies]
windows-sys = { version = "0.61.2", features = ["Win32_UI_Input_XboxController"] }

[lib]
path = "src/lib.rs"
